version: '2'
services:

  proxy:
    image: nginx:latest
    ports:
        - "8200:80"
    links:
        - apollo
        - galaxy
        - tripal
    volumes:
        - "./nginx/conf:/etc/nginx/conf.d"

  galaxy:
    image: quay.io/erasche/docker-galaxy-annotation
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
        GALAXY_WEBAPOLLO_URL: "http://apollo:8080/apollo"
        GALAXY_WEBAPOLLO_EXT_URL: "/apollo"
        GALAXY_WEBAPOLLO_PASSWORD: "password"
        GALAXY_WEBAPOLLO_USER: admin@local.host
        GALAXY_SHARED_DIR: /apollo-data

  apollo:
    image: gmod/apollo:latest
    links:
      - "apollo_db:db"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://tripal_db/postgres"
    volumes_from:
        - "galaxy:ro"

  apollo_db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: password

  postgrest:
    image: erasche/postgrest:latest
    links:
      - "tripal_db:db"
    ports:
      - "8300:8000"
    environment:
      POSTGREST_JWT_SECRET: thisisnotarealsecret
      POSTGREST_SCHEMA: public
      PG_PASSWORD: password
      PG_DB: postgres

  ngadmin:
    image: quay.io/erasche/chado-angular-admin:latest
    links:
      - "postgrest"
    ports:
      - "8400:8080"

  chado_jb:
    image: quay.io/erasche/chado-jbrowse-connector:latest
    environment:
      - POSTGRES_PASSWORD=password
    links:
      - "tripal_db:db"
    ports:
      - "8500:8500"

  tripal_db:
    image: erasche/chado:latest
    environment:
      - POSTGRES_PASSWORD=password
        # The default chado image would try to install the schema on first run,
        # we just want the tools to be available.
      - INSTALL_CHADO_SCHEMA=0

  tripal:
    image: erasche/tripal:latest
    links:
      - tripal_db:postgres
    volumes:
      - /var/www/html/sites
      - /var/www/private
    environment:
      UPLOAD_LIMIT: 20M
      MEMORY_LIMIT: 128M
      BASE_URL: "http://localhost:8080/tripal"
      BASE_URL_PROTO: "http://"
      # FIXME Deprecated ENV var added for compatibility: https://docs.docker.com/compose/link-env-deprecated/
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_PORT_5432_TCP: tcp://postgres:5432
      POSTGRES_ENV_POSTGRES_PASSWORD: password
    ports:
      - "8080:80"
